### ISSUE TITLE
SelectSession에 한번 들어갔다와야 EmptyTextLayout이 정상적으로 출력되는 문제

### ISSUE THREAD

**Issue by ghost** [GDG-SSU/deviewsched-android#10]

**Comment by enghqii** [comment]
MainActivity -> 네비게이션 드로워에 있는 'Favorite Session' -> 액션바 우측 상단의 별 모양 버튼을 눌렀을때 뜨는 익셉션을 언급하신건가요?

**Comment by enghqii** [comment]
```
12-07 23:38:29.706 4067-4067/com.gdgssu.android_deviewsched E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.gdgssu.android_deviewsched, PID: 4067
                                                                              java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                                                  at com.gdgssu.android_deviewsched.ui.selectsession.SelectSessionListAdapter.setTwoSpeakerInfo(SelectSessionListAdapter.java:162)
                                                                                  at com.gdgssu.android_deviewsched.ui.selectsession.SelectSessionListAdapter.getView(SelectSessionListAdapter.java:108)
                                                                                  at android.widget.AbsListView.obtainView(AbsListView.java:2346)
                                                                                  at android.widget.ListView.makeAndAddView(ListView.java:1875)
                                                                                  at android.widget.ListView.fillDown(ListView.java:702)
                                                                                  at android.widget.ListView.fillFromTop(ListView.java:763)
                                                                                  at android.widget.ListView.layoutChildren(ListView.java:1684)
                                                                                  at android.widget.AbsListView.onLayout(AbsListView.java:2148)
                                                                                  at android.view.View.layout(View.java:16630)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                                  at android.view.View.layout(View.java:16630)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                  at android.view.View.layout(View.java:16630)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                                  at android.view.View.layout(View.java:16630)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                  at android.view.View.layout(View.java:16630)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                                  at android.view.View.layout(View.java:16630)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                  at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                                                  at android.view.View.layout(View.java:16630)
                                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                                  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
                                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
                                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                  at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by ghost** [comment]
아 저 크래시는 아래 커밋을 통해서 수정되었습니다.

https://github.com/GDG-SSU/deviewsched-android/commit/df389ece9282fce1ab8f92b9cef32b2f25619c53

이 이슈에 달았던 문제는 크래시까지 터지는 문제는 아닌데, 로그인과 관심세션 등록 상태에 따른 뷰로직이 꼬인게 있는것 같습니다. 해결하기 크게 어려운부분은 아니라고 생각합니다.

**Comment by ghost** [comment]
#15 에서 해결되었습니다.
